#version: "3"
#services:
#  frontend:
#    build: ./frontend/
#    ports:
#      - "5000:5000"
#  backend:
#    build: ./backend/
#    ports:
#      - "3000:3000"

version: "3.3"
services:
    db:
        container_name: thyme-db
        restart: always
        image: thyme-db
        build:
            context: ./db
        volumes:
            - db:/var/lib/postgresql/data
            - ./db/scripts:/src/app
        networks:
            - local
        ports:
            - 5432:5432
        env_file:
            - ./.env

    graphql:
        container_name: thyme-graphql
        restart: always
        image: thyme-graphql
        build:
            context: ./graphql
        depends_on:
            - db
        networks:
            - local
        ports:
            - 5433:5433

        env_file:
            - ./.env

        command:
            [
                "postgraphile",
                "-n",
                "0.0.0.0",
                "--enhance-graphiql",
                "--subscriptions",
                "--watch",
                "--show-error-stack",
                "json",
                "--enable-query-batching",
                "--legacy-functions-only",
                "--dynamic-json",
                "--connection",
                "${DATABASE_URL}",
                "--port",
                "5433",
                "--schema",
                "public,private",
                "--append-plugins",
                "postgraphile-plugin-connection-filter,@graphile-contrib/pg-simplify-inflector",
            ]

    api-gateway:
        container_name: thyme-api-gateway
        restart: always
        image: thyme-api-gateway
        build:
            context: ./api_gateway
        volumes:
            - ./api_gateway:/usr/src/app
        depends_on:
            - graphql
        networks:
            - local
        ports:
            - 8080:8080
        env_file:
            - ./.env
        command:
            ["npm", "start"]

    cron:
        container_name: thyme-cron
        restart: always
        depends_on:
            - graphql
        build:
            context: ./cron
        networks: 
            - local
        volumes:
            - ./cron:/src/app
        ports:
            - 5665:5665
        env_file:
            - ./.env

networks:
    local:
        driver: bridge
volumes:
    db:
